### PR TITLE
added script for gathering metrics

### PR DESCRIPTION
**Pull request by pablomendezroyo**

### CODE REVIEW

**Review by dapplion — APPROVED** [review]

**Comment by dapplion** [comment]
Build fails check https://app.netlify.com/sites/xenodochial-fermat-fb6b53/deploys/6019752f64a02e0007202ebb

**Review by dapplion — CHANGES_REQUESTED** [review]
Build fails check https://app.netlify.com/sites/xenodochial-fermat-fb6b53/deploys/6019752f64a02e0007202ebb

**Comment by dapplion** [comment]
Can you build the site locally and validate that the script is actually injected into the HTML? I don't see it in the preview

**Comment by dapplion** [comment]
Can you inspect the HTML and show a screen capture proving that the script is actually injected?

**Comment by pablomendezroyo** [comment]
Issues reported:
- Old node engine
- Old versions in general
- Old react syntax?

image

**Review by dapplion — APPROVED** [review]

**Pull request merged**
